   vich_uploader:
       db_driver: orm # other options are mongodb, propel, phpcr
       mappings:
           product_image:
               uri_prefix: /uploads/products
               upload_destination: '%kernel.project_dir%/public/uploads/products'
               namer: vich_uploader.namer_origname
               inject_on_load: false
               delete_on_update: true
               delete_on_remove: true
